name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ahmedbhai/reactjs-app .
      - name: Publish image to Docker Hub
        run: docker push ahmedbhai/reactjs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Install Docker
        run: sudo apt-get update && sudo apt-get install -y docker.io
      - name: Add user to Docker group
        run: sudo usermod -aG docker $USER
      - name: Restart the Docker service
        run: sudo service docker restart
      - name: Pull image from Docker Hub
        run: docker pull ahmedbhai/reactjs-app:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainer ahmedbhai/reactjs-app

